import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Import fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata
export const metadata = {
  title: "portfolio",
  description: "Generated by create next app",
};

// Root Layout Component
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="relative bg-white">
        {/* Background Dotted Effect */}
        <div className="absolute inset-0 bg-[radial-gradient(#000000_1px,transparent_1px)] bg-[length:10px_10px] opacity-10 pointer-events-none"></div>

        {/* Left Border and Main Content */}
        <main className="border-l-4 border-black ml-10 relative z-10 min-h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}
